### PR TITLE
Modal design updates

### PR DESCRIPTION
**Pull request by vicmgs**

### CODE REVIEW

**Comment by allenan** [comment]
looks nice! one thing i noticed is that modals seem to get that selected outline, you can see it in your last image. maybe we should disable that?

**Comment by allenan** [comment]
the payment modal appears to be wider than the others. as long as we're looking at modals maybe we should make that one more consistent with the others?

**Comment by vicmgs** [comment]
widths fix added

**Comment by allenan** [comment]
also the register hotspot modal is kind of close to the bottom of the app when it's at its min height:

image

maybe we could reduce the `top` amount

**Pull request merged**
