### PR TITLE
Fetch gateways on component mount

### PR DESCRIPTION
**Pull request by vicmgs**

### CODE REVIEW

**Comment by allenan** [comment]
why is one of these longer than the others?
image
I think we might need to use the monospace font for addresses so they have consistent lengths

**Comment by allenan** [comment]
also when you click on one, you get `undefined` in the top area:

image

**Comment by vicmgs** [comment]
the undefined and the non-monospace text is because the designs is saying to show gateway name. Since we do not have gateway name, switch to monospaced address instead?

**Comment by allenan** [comment]
yeah let's just use address for now I guess

**Pull request merged**
