### PR TITLE
Restyle notifications

### PR DESCRIPTION
**Pull request by vicmgs**
These notifications are manually generated, the missing fields will be populated in a real notification.
screen shot 2019-01-09 at 2 17 05 pm
screen shot 2019-01-09 at 2 17 09 pm
screen shot 2019-01-09 at 2 17 13 pm
screen shot 2019-01-09 at 2 17 19 pm
screen shot 2019-01-09 at 2 17 23 pm
screen shot 2019-01-09 at 2 17 26 pm

### CODE REVIEW

**Comment by allenan** [comment]
for the Server Error notification, could we call that something else? It just seems odd to refer to a "server" when we don't really have one. Also can we attempt to pass through some description of the error rather than just saying "sorry try again"? I think that error was confusing people when their token had expired or whatever that issue was. that may require a node update so we can make a separate CH for it

**Comment by allenan** [comment]
The "no new notifications" card feels really long for some reason:

image

maybe the width could be a bit smaller on that one?

**Comment by allenan** [comment]
We should show the `animalHash` of the hotspot address in addition to the address wherever available

**Comment by allenan** [comment]
we should also show the user-defined account name and hotspot name if those are available as well, to give the user more context about what's being added where, or which hotspot is asserting

**Comment by vicmgs** [comment]
screen shot 2019-01-09 at 3 58 40 pm
screen shot 2019-01-09 at 4 36 43 pm
screen shot 2019-01-09 at 4 37 17 pm

**Pull request merged**
